<a href="https://colab.research.google.com/github/yunirajagukguk/GenAI-Tugas-4/blob/main/RNN_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**RNN Basic**

In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

print('Tensorflow: {}'.format(tf.__version__))

plt.rcParams['figure.figsize'] = (16, 10)
plt.rc('font', size=15)

Tensorflow: 2.20.0


Simple RNN Cell

In [ ]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [ ]:
X_data = np.array([[h]], dtype=np.float32)
X_data.shape

(1, 1, 4)

In [ ]:
hidden_size = 2
cell = tf.keras.layers.SimpleRNNCell(units=hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(X_data)

print("X_data: {}, shape: {}".format(X_data, X_data.shape))
print("output: {}, shape: {}".format(outputs, outputs.shape))
print("states: {}, shape: {}".format(states, states.shape))

X_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
output: [[[0.5497398  0.07063385]]], shape: (1, 1, 2)
states: [[0.5497398  0.07063385]], shape: (1, 2)


Mentioned before, we can also build it with layer API.

In [ ]:
rnn_2 = tf.keras.layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
outputs, states = rnn_2(X_data)

print("X_data: {}, shape: {}".format(X_data, X_data.shape))
print("output: {}, shape: {}".format(outputs, outputs.shape))
print("states: {}, shape: {}".format(states, states.shape))

X_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
output: [[[-0.6373711  -0.20758513]]], shape: (1, 1, 2)
states: [[-0.6373711  -0.20758513]], shape: (1, 2)


Unfolding multiple sequences

In [ ]:
X_data = np.array([[h, e, l, l, o]], dtype=np.float32)
X_data.shape

(1, 5, 4)

In [ ]:
cell = tf.keras.layers.SimpleRNNCell(units=hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(X_data)

print("X_data: {}, shape: {}\n".format(X_data, X_data.shape))
print("output: {}, shape: {}\n".format(outputs, outputs.shape))
print("states: {}, shape: {}".format(states, states.shape))

X_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4)

output: [[[ 0.7446132  -0.00980966]
  [-0.8448543   0.25514683]
  [ 0.7108736  -0.17715016]
  [-0.5641086  -0.6053631 ]
  [-0.14551646  0.5421882 ]]], shape: (1, 5, 2)

states: [[-0.14551646  0.5421882 ]], shape: (1, 2)


Batching Input

In [ ]:
X_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)
X_data.shape

(3, 5, 4)

In [ ]:
cell = tf.keras.layers.SimpleRNNCell(units=hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(X_data)

print("X_data: {}, shape: {}\n".format(X_data, X_data.shape))
print("output: {}, shape: {}\n".format(outputs, outputs.shape))
print("states: {}, shape: {}".format(states, states.shape))

X_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4)

output: [[[ 0.3695654  -0.3650049 ]
  [-0.1307267   0.87915206]
  [ 0.5423081  -0.783199  ]
  [ 0.7622682   0.60181   ]
  [ 0.52335966 -0.26602086]]

 [[-0.4110503   0.7406211 ]
  [-0.50370157 -0.53709066]
  [ 0.00943835  0.27595362]
  [ 0.5701757  -0.41002372]
  [ 0.7967676   0.3205695 ]]

 [[ 0.5325253  -0.16340245]
  [ 0.7978217   0.08263095]
  [ 0.34853646  0.7615362 ]
  [ 0.030678    0.25150162]
  [ 0.58152956 -0.3868272 ]]], shape: (3, 5, 2)

states: [[ 0.52335966 -0.26602086]
 [ 0.7967676   0.3205695 ]
 [ 0.58152956 -0.3868272 ]], shape: (3, 2)
